export const EVENT_TYPES = {
    CLICK_EVENT: "click",
    IMPRESSION_EVENT: "impression",
    SCREEN_VIEW_EVENT: "screenview",
    MODAL_VIEW_EVENT: "modalview",
    MODAL_CLOSE_EVENT: "modalclose",
    SWIPE_EVENT: "swipe",
    API_EVENT: "api_call",
    ERROR_EVENT: "error",
    APPS_TRACKED: "apps_tracked",
};

export const PLATFORM = {
    IOS: "ios",
    ANDROID: "android",
};

export const SCREEN_NAMES = {
    CATEGORY: "category",
    HOME: "home",
    SEARCH: "search",
    LANDING: "landing",
    WALLET: "wallet",
    SCHEDULE: "order-calendar",
    AUTH_LOGIN: "login",
    AUTH_OTP: "otp",
    PROFILE: "profile",
    REGISTER: "register",
    ADDRESS: "address",
    ADDRESS_TYPE: "address-type",
    ADDRESS_SEARCH: "address-search-location",
    SOCIETY_SEARCH: "address-search-society",
    SOCIETY_DETAILS_SEARCH: "address-search-society-details",
    ADDRESS_REVIEW: "address-instructions",
    ADDRESS_FORM: "address-form-v2",
    ADDRESS_MAP: "address-map-view-V2",
    ADDRESS_MAP_EDIT: "address-map-edit-view-V2",
    RECHARGE_SUBSCRIPTION: "recharge-subscription",
    CART: "cart-page",
    SUBSCRIPTION_LIST: "subscriptions",
    SUBSCRIPTION_CREATE: "create-subscription-v2",
    SUBSCRIPTION_DETAILS: "subscription-details",
    SUBSCRIPTION_SUMMARY: "subscription-orders",
    THANK_YOU: "order-success-screen",
    SUBSCRIPTION_DELIVERY_SCHEDULE: "subscription-delivery-schedule",
    CATEGORY_ESSENTIALS: "category-essentials",
    SUPPORT: "support",
    FAQ: "faq",
    SUGGESTION: "suggestions-page",
    CITY_SELECTION: "city-selection",
    COLLECTION: "collection-page",
    SUPER_CREDITS_ONBOARDING: "supr-credits-onboarding",
    OOS_ALTERNATES: "out-of-stock",
    SUPR_PASS: "supr-pass",
    VACATION: "vacation",
    SUPR_PASS_FAQ: "supr-pass-faq",
    SUPR_PASS_ACTIVITY: "supr-pass-activity",
    COMPLAINTS: "complaints",
    DELIVERY_PROOF: "delivery-photo",
    REFERRAL: "referral",
    REFERRAL_FAQ: "referral-faq",
    REFERRAL_REWARDS: "referral-rewards",
};

export const DEFAULT_SEGMENT_TRAITS = {
    OBJECT_NAME: "-",
    OBJECT_VALUE: "-",
    CONTEXT: "-",
};

export const MODAL_NAMES = {
    EDIT_SUBSCRIPTION: "edit-subscription-modal",
    EDIT_FREQUENCY: "edit-frequency-modal",
    CREATE_SUBSCRIPTION: "create-subscription-modal",
    CHANGE_DATE: "change-date-modal",
    PAUSE_ORDER: "pause-order-modal",
    CONFIRM_RESUME: "confirm-resume-modal",
    CONFIRM_PAUSE: "confirm-pause-modal",
    EDIT_ADDON_DELIVERY: "edit-addon-delivery",
    EDIT_SUBSCRIPTION_DELIVERY: "edit-subscription-delivery",
    FLAT_SEARCH: "flat-search",
    TOWER_SEARCH: "tower-search",
    PAUSE_CONFIRM: "confirm-pause-modal",
    RESUME_CONFIRM: "confirm-resume-modal",
    ITEM_REMOVE_CONFIRM: "item-remove-confirm",
    REMOVE_SUB_FROM_CART: "remove-subscription-cart-modal",
    EDIT_ADDRESS: "edit-address",
    BILLING: "billing",
    CANCEL_CONFIRM_SUBSCRIPTION: "cancel-confirm-subscription",
    PRODUCT_PREVIEW: "product-preview",
    SUBSCRIBE_ITEM: "subscribe-item",
    COUPON_ADD_ADDRESS: "coupon-add-address",
    APP_UPDATE: "app-update",
    OOPS_ERROR: "oops-error",
    DOOR_BELL: "door-bell",
    WHATSAPP_OPT_IN: "whatsapp-opt-in",
    UPDATE_ADDRESS_COMPONENT: "update-address-component",
    UPDATE_BLOCK: "update-block",
    UPDATE_FLAT_NO: "update-flat-no",
    UPDATE_FLOOR_NO: "update-floor-no",
    UPDATE_SOCIETY_NAME: "update-society-name",
    ADDRESS_REVIEW: "address-review",
    APP_RATING: "app-rating",
    ADDRESS_RETRO: "address-retro",
    GENERIC_NUDGE: "generic-nudge",
    EXIT_CART: "exit-cart-prompt",
    CAMPAIGN_POPUP: "campaign-popup",
    REQUEST_PRODUCT: "request-product",
    CREATE_SUBSCRIPTION_DELIVERIES: "top-up-settings",
    CREATE_SUBSCRIPTION_START_DATE: "subscription-start-date",
    CREATE_SUBSCRIPTION_FREQUENCY: "repeat-settings",
    SUPR_CREDITS_MODAL: "supr-credits-onboarding-modal",
    CART_COUPON_MODAL: "cart-coupon-modal",
    ORDER_FEEDBACK: "order-rating",
    FEEDBACK_COMMENT: "feedback-comment",
    DELIVERY_FEE_INFO_MODAL: "delivery-fee-info-modal",
    REFERRAL_SUCCESS_MODAL: "referral-success-screen",
    PN_MODAL: "push-notification-modal",
    CATEGORY_SKUS_UNAVAILABLE_MODAL: "category-skus-unavailable-modal",
    SUB_CATEGORY_SKUS_UNAVAILABLE_MODAL: "sub-category-skus-unavailable-modal",
    COLLECTION_SKUS_UNAVAILABLE_MODAL: "collection-skus-unavailable-modal",
    ORDER_THROTTLING: "user-order-throttling-modal",
    DELIVERY_FEEDBACK_SUCCESS: "delivery-feedback-success",
    CART_ALTERNATE_DELIVERY_DETAILS: "cart-alternate-delivery-details",
    VACATION_START_DATE: "vacation-start-date",
    COMPLAINTS_SUPPORT: "need-immediate-help",
    SUPPORT_FAQ_COMPLAINTS: "need-immediate-help",
    AUTO_DEBIT_PAYMENT_MODES: "auto-debit-payment-modes",
    AUTO_DEBIT_SUCCESS_MODAL: "auto-debit-success-modal",
    AUTO_ADD_SUPR_PASS_PROMPT: "auto-add-supr-pass-prompt",
    AUTO_DEBIT_PAYMENT_FAILURE: "supr-access-auto-debit-payment-failure-nudge",
};

export const DEFAULT_API_STATUS_CODE = 999;

export const IMPRESSION_VISIBILITY_RATIO = 0.5;

export const ANALYTICS_OBJECT_NAMES = {
    CLICK: {
        BACK_BUTTON: "back-button",
        TRY_AGAIN: "try-again",
        CONTINUE: "continue",
        SEARCH_CLEAR: "clear-results",
        SELECT_CITY: "select-city",
        LET_US_KNOW: "let-us-know",
        SUBMIT: "submit",
        ADD_PRODUCT: "add-product",
        SUBSCRIBE_PRODUCT: "subscribe-product",
        PRODUCT_QUANTITY_PLUS: "quantity-plus",
        PRODUCT_QUANTITY_MINUS: "quantity-minus",
        CATEGORY_TILE: "category",
        PAUSE_BUTTON: "pause-button",
        UNPAUSE_BUTTON: "unpause-button",
        PAUSE_CONFIRM: "confirm-pause-button",
        UNPAUSE_CONFIRM: "confirm-resume-button",
        PAUSE_MONTH_CHANGE: "month-change",
        PAUSE_START_DATE: "start-date",
        PAUSE_END_DATE: "end-date",
        CREATE_SUBSCRIPTION_DELIVER_ONCE: "buy-one-day",
        CREATE_SUBSCRIPTION_NEXT: "next-button",
        CREATE_SUBSCRIPTION_NUM_DELIVERIES: "num-deliveries",
        CREATE_SUBSCRIPTION_STEP_PREFIX: "button-step",
        CREATE_SUBSCRIPTION_DELIVERY_FREQ: "delivery-frequency",
        CREATE_SUBSCRIPTION_WEEKDAYS: "weekdays",
        CREATE_SUBSCRIPTION_CHOOSE_DATE: "choose-date",
        UPDATE_NOW: "update-now",
        REMIND_LATER: "remind-later",
        PN_GOT_IT: "pn-got-it",
        FREQUENCY_MODAL_REPEAT_DAYS: "repeat-days",
        FREQUENCY_MODAL_CONFIRM_REPEAT: "confirm-repeat",
        SET_VACATION: "set-vacation",
        COMPLAINTS_REACH: "reach-us",
        CALL_BUTTON: "call-button",
        CHAT_BUTTON: "chat-button",
    },
    IMPRESSION: {
        NO_PRODUCT_FOUND: "no-product-found",
        MODAL: "modal",
        FLOATING_CART: "floating-cart",
        FRESHBOT_INIT: "freshbot-script-initialize",
        FRESHBOT_OPEN: "freshbot-view-initiate",
        LANDING_OOPS: "landing-page-oops",
        DELIVERY_FEE_BLOCK: "delivery-fee-block",
        FRESHBOT_INIT_ERROR: "freshbot-script-initialize-error",
        FRESHBOT_JS_ERROR: "freshbot-js-initialize-error",
        FRESHCHAT_LOAD: "freshchat-initiate",
        CART_CHANGES: "cart-changes",
        GET_SUPR_ACCESS: "get-supr-access",
        SUPR_ACCESS_APPLIED: "supr-access-applied",
        SUPR_ACCESS_SERVICE_FEE_BANNER: "supr-access-service-fee-banner",
        COMPLAINTS_VIEW: "complaint-view",
        COMPLAINT_CONFIG: "complaint-config",
        SUPPORT_CONFIG: "support-config",
    },
};

export const ANALYTICS_OBJECT_VALUES = {
    ACTIVE: "active",
    INACTIVE: "InActive",
};

export const CALENDAR_MONTH_CHANGE_DIRECTIONS = {
    LEFT: "left",
    RIGHT: "right",
};

export const DEFAULT_CURRENCY = "INR";

export enum ECOMMERCE_ANALYTICS_EVENTS {
    PRODUCT_ADDED = "Product Added",
    PRODUCT_REMOVED = "Product Removed",
    PRODUCT_VIEWED = "Product Viewed",
    CHECKOUT_STARTED = "Checkout Started",
    ORDER_COMPLETED = "Order Completed",
    CART_VIEWED = "Cart Viewed",
}

export enum MOENGAGE_EVENTS {
    LOGGED_IN = "LOGGED_IN",
    ADDRESS_CHANGED = "ADDRESS_CHANGED",
    WALLET_RECHARGE = "WALLET_RECHARGE",
    DELIVER_ONCE = "DELIVER_ONCE",
    DELIVERY_CANCELLED = "DELIVERY_CANCELLED",
    SUBSCRIPTION_STARTED = "SUBSCRIPTION_STARTED",
    SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED",
    SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
    INITIATE_SUBSCRIPTION = "INITIATE_SUBSCRIPTION",
    SUBSCRIPTION_ADD_TO_CART = "SUBSCRIPTION_ADD_TO_CART",
    VACATION_UPDATED = "VACATION_UPDATED",
    VIEWED_PRODUCT_LIST = "VIEWED_PRODUCT_LIST",
    ADD_TO_CART = "ADD_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    INITIATE_CHECKOUT = "INITIATE_CHECKOUT",
    INITIATE_RECHARGE = "INITIATE_RECHARGE",
    COMPLETE_PURCHASE_SUMMARY = "COMPLETE_PURCHASE_SUMMARY",
    COMPLETE_PURCHASE_DETAILS = "COMPLETE_PURCHASE_DETAILS",
    SIGNED_UP = "SIGNED_UP",
    PROFILE_COMPLETED = "PROFILE_COMPLETED",
    CLICK_EVENTS = "CLICK_EVENTS",
}

export const APPS_FLYER_EVENTS = {
    COMPLETE_REGISTRATION: "af_complete_registration",
    CONTENT_VIEW: "af_content_view",
    LIST_VIEW: "af_list_view",
    ADD_TO_CART: "af_add_to_cart",
    REMOVE_FROM_CART: "remove_from_cart",
    INITIATED_CHECKOUT: "af_initiated_checkout",
    PURCHASE: "af_purchase",
    FIRST_ORDER: "af_first_order",
};

export const SMARTLOOK_EVENT_TYPES = {
    SCREEN_VIEW_EVENT: "screenview",
};

export const OOS_ANALYTICS_TEXTS = {
    TYPE: "type",
    QUANTITY: "quantity",
    UNIT_MRP: "unit-mrp",
    UNIT_PRICE: "unit-price",
    START_DATE: "start-date",
    RECHARGE_QTY: "recharge-qty",
    SCHEDULE_DATE: "schedule-date",
    QTY_PER_DELIVERY: "qty-per-delivery",
    OOS_SKU_ID: "oos-sku-id",
    OOS_PARENT_ID: "oos-parent-id",
    OOS_PREFERRED_FLOW: "preferred-flow",
    OOS_AVAILABLE_DATE: "next-available-date",
};

export const SA_IMPRESSIONS_IS_ENABLED = {
    HOME_FEATURED: true,
    COLLECTION_WIDGET: true,
    COLLECTION_SEE_ALL: true,
    COLLECTION_CARD: true,
    COLLECTION_HERO_GRID: true,
    SUPR_TILE: true,
    SUB_CATEGORY_TILE: true,
    SEARCH_BOX: true,
    CATEGORY_PRODUCT_GROUP: true,
    SUBSCRIPTION_PRODUCTS: true,
    ANALYTICS_MODAL_VIEW_DIRECTIVE_CLOSE: true,
};
