export interface ApiRoutes {
    [key: string]: string;
}

export const API_ROUTES: ApiRoutes = {
    SETTINGS: "v1/settings/",
    EXPERIMENTS: "v1/experiments/",
    VERSION: "v1/check-version/",
    CATEGORY: "v2/products/category/",
    CATEGORY_DETAILS: "v2/products/category/",
    FEATURED_LIST_ITEMS: "v2/products/feature-catalog/",
    ESSENTIAL_CATEGORIES: "v2/products/essential/all/",
    COLLECTION_LIST: "v2/collection-views/",
    COLLECTION_DETAILS: "v2/collection-view/",
    ADDON: "v2/addon/",
    SUBSCRIPTION: "v2/subscription/",
    SUBSCRIPTION_INSTRUCTION: "v2/subscription-instruction/",
    SUBSCRIPTION_TRANSACTIONS: "v2/subscription-transactions/",
    VACATION: "v2/accounts/vacation/",
    ORDER_HISTORY: "v2/order-history/",
    CART_VALIDATE: "v2/cart/validate/",
    CART_CHECKOUT: "v2/cart/checkout/",
    ADDRESS: "v3/address/",
    CREATE_ADDRESS: "v3/address/save",
    PREMISE_SEARCH: "v3/address/premise/search",
    PREMISE_POPULAR_SEARCH: "v3/address/premise/search/popular",
    PREMISE_ADDRESS: "v3/address/premise/",
    SCHEDULE: "v3/schedule/",
    SKU: "v3/products/sku/",
    PROFILE: "v3/accounts/profile/",
    REQUEST: "v1/accounts/request/",
    WALLET_TRANSACTIONS: "v1/transactions/",
    WALLET_TRANSACTIONS_V2: "v2/transactions/",
    WALLET_BALANCE: "v1/balance/",
    WALLET_BALANCE_V2: "v2/balance/",
    PAYMENT_GATEWAY: "v1/payment/",
    PASSWORD: "v1/accounts/password/",
    LOGIN: "v1/accounts/login/",
    FAQ: "v1/support/faq/",
    SUPPORT: "v1/support/",
    LOCATION_STATUS: "v1/accounts/location-status",
    FEEDBACK_OPTIONS: "v1/feedback/options",
    FEEDBACK_ACTION: "v1/feedback/action",
    FEEDBACK: "v1/feedback",
    REVERSE_GEOCODE: "v1/reverse-geocode",
    LOCATION_SUGGESTIONS: "v1/places-autocomplete",
    DELIVERY_STATUS: "v2/delivery-summary/",
    NUDGE_LIST: "v2/nudges/",
    RECHARGE_COUPON_VALIDATE: "v1/payment-offer-validate/",
    RECHARGE_COUPON_OFFERS: "v2/recharge-coupon-offers/",
    PAST_ORDER: "v2/recommendation/past-order/",
    OVERALL_ORDER_FEEDBACK: "v1/collect_feedback_request/",
    ORDER_FEEDBACK: "v1/feedback_info/",
    ORDER_FEEDBACK_RESPONSE: "v1/feedback_response/",
    PAYMENT_OFFERS: "v1/payment-offer/",
    SIMILAR_PRODUCTS: "v2/recommendation/alternative-skus/",
    SUPR_PASS_INFO: "v2/purchase/supr-pass/",
    SKU_NOTIFY: "v2/products/customer-sku/notify/",
    HOME_LAYOUT: "v3/collection-views/",
    COMPLAINT_LIST: "v1/complaints/status/self_serve/",
    ANONYMOUS_TOKEN: "v1/accounts/anonymous-user-token/",
    BROWSE_CATEGORY: "v2/browse/products/category/",
    BROWSE_CATEGORY_DETAILS: "v2/browse/products/category/",
    BROWSE_SKU: "v3/browse/products/sku/",
    BROWSE_FEATURED_LIST_ITEMS: "v2/browse/products/feature-catalog/",
    BROWSE_COLLECTION_LIST: "v2/browse/collection-views/",
    BROWSE_COLLECTION_DETAILS: "v2/browse/collection-view/",
    BROWSE_ESSENTIAL_CATEGORIES: "v2/browse/products/essential/all/",
    BROWSE_HOME_LAYOUT: "v3/browse/collection-views/",
    BROWSE_FAQ: "v1/browse/support/faq/",
    CONTACT_SUPPORT: "v1/self_serve/contact-us/",
    PAYMENT_METHODS: "v1/payment-methods",
    REFERRAL: "v2/referral/",
    AUTODEBIT_PAYMENT_ORDER: "v1/razorpay-payment-order/",
    AUTODEBIT_PAYMENT_METHOD: "v1/razorpay-auto-debit-payment-methods/",
    AUTODEBIT_SETUP: "v1/purchase/supr-pass/setup-auto-debit/ ",
    CANCEL_AUTODEBIT: "v1/purchase/supr-pass/cancel-auto-debit/",
};
